### ISSUE TITLE
Bitmap is stored as `Buffer<usize>` instead of `Buffer<u8>`?

### ISSUE THREAD

**Issue by jorgecarleitao** [teratide/narrow#23]
Arrow's in-memory format stores bitmaps as `&[u8]` because their positions are

```
# each number is a bit
[7, 6, 5, 4, 3, 2, 1, 0], [15, 14, 13, 12, 11, 10, 9, 8]
```

However, I see that you use `usize`, which is quite interesting! Is the idea that `bitvec` automatically picks the right bits based on the position? I.e. `bitmap[8]` will take the equivalent of first bit of the second byte in `usize`?

This could allow for an optimization whereby we use `u32` for primitives with 32 lanes, `u16` for primitives with 16 lanes, etc.

**Comment by mbrobbel** [comment]
l'm using `usize` there because of how I implemented `FromIterator<bool>` for `Bitmap`. Every `N` `bool`s in the iterator (where `N` is the number of bits in a `usize`) result in a write to memory. My intuition is that using `usize` here instead of `u8` results in more efficient arithmetics and reduces the number of writes to memory. However I could be wrong and should validate this with benchmarks and by inspecting the optimized compiler output.

`bitvec` supports both reading and writing LSB-first and MSB-first.

> This could allow for an optimization whereby we use u32 for primitives with 32 lanes, u16 for primitives with 16 lanes, etc.

Yes this makes sense, a single read to get the validity bits for all the lanes.

**Comment by mbrobbel** [comment]
Actually it turns out that my understanding was wrong and the current implementation is not according to the [specification](https://arrow.apache.org/docs/format/Columnar.html#validity-bitmaps). I'll fix it. Thanks!
